/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("org.springframework.boot") version "3.5.0"
    id("io.spring.dependency-management") version "1.1.4" // 의존성 관리 플러그인 추가  
}

repositories {
    mavenCentral()
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.oauth2.client)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.projectlombok.lombok)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    runtimeOnly(libs.com.h2database.h2)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.security.spring.security.test)
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.4")
}

group = "com.clone"
version = "0.0.1-SNAPSHOT"
description = "karrotbackend"
java.sourceCompatibility = JavaVersion.VERSION_17

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
